export default {
  Continue: { code: 100, message: 'Continue' },
  SwitchingProtocols: { code: 101, message: 'Switching Protocols' },
  Processing: { code: 102, message: 'Processing' },
  OK: { code: 200, message: 'OK' },
  Created: { code: 201, message: 'Created' },
  Accepted: { code: 202, message: 'Accepted' },
  NonAuthoritativeInformation: {
    code: 203,
    message: 'Non-Authoritative Information'
  },
  NoContent: { code: 204, message: 'No Content' },
  ResetContent: { code: 205, message: 'Reset Content' },
  PartialContent: { code: 206, message: 'Partial Content' },
  MultiStatus: { code: 207, message: 'Multi-Status' },
  AlreadyReported: { code: 208, message: 'Already Reported' },
  IMUsed: { code: 226, message: 'IM Used' },
  MultipleChoices: { code: 300, message: 'Multiple Choices' },
  MovedPermanently: { code: 301, message: 'Moved Permanently' },
  Found: { code: 302, message: 'Found' },
  SeeOther: { code: 303, message: 'See Other' },
  NotModified: { code: 304, message: 'Not Modified' },
  UseProxy: { code: 305, message: 'Use Proxy' },
  SwitchProxy: { code: 306, message: 'Switch Proxy' },
  TemporaryRedirect: { code: 307, message: 'Temporary Redirect' },
  PermanentRedirect: { code: 308, message: 'Permanent Redirect' },
  BadRequest: { code: 400, message: 'Bad Request' },
  Unauthorized: { code: 401, message: 'Unauthorized' },
  Forbidden: { code: 403, message: 'Forbidden' },
  NotFound: { code: 404, message: 'Not Found' },
  MethodNotAllowed: { code: 405, message: 'Method Not Allowed' },
  NotAcceptable: { code: 406, message: 'Not Acceptable' },
  RequestTimeout: { code: 408, message: 'Request Timeout' },
  Conflict: { code: 409, message: 'Conflict' },
  Gone: { code: 410, message: 'Gone' },
  LengthRequired: { code: 411, message: 'Length Required' },
  PreconditionFailed: { code: 412, message: 'Precondition Failed' },
  PayloadTooLarge: { code: 413, message: 'Payload Too Large' },
  URITooLong: { code: 414, message: 'URI Too Long' },
  UnsupportedMediaType: { code: 415, message: 'Unsupported Media Type' },
  RangeNotSatisfiable: { code: 416, message: 'Range Not Satisfiable' },
  ExpectationFailed: { code: 417, message: 'Expectation Failed' },
  ImATeapot: { code: 418, message: "I'm a teapot" },
  MisdirectedRequest: { code: 421, message: 'Misdirected Request' },
  UnprocessableEntity: { code: 422, message: 'Unprocessable Entity' },
  Locked: { code: 423, message: 'Locked' },
  FailedDependency: { code: 424, message: 'Failed Dependency' },
  UnorderedCollection: { code: 425, message: 'Unordered Collection' },
  UpgradeRequired: { code: 426, message: 'Upgrade Required' },
  PreconditionRequired: { code: 428, message: 'Precondition Required' },
  TooManyRequests: { code: 429, message: 'Too Many Requests' },
  RequestHeaderFieldsTooLarge: {
    code: 431,
    message: 'Request Header Fields Too Large'
  },
  UnavailableForLegalReasons: {
    code: 451,
    message: 'Unavailable For Legal Reasons'
  },
  InternalServerError: { code: 500, message: 'Internal Server Error' },
  NotImplemented: { code: 501, message: 'Not Implemented' },
  BadGateway: { code: 502, message: 'Bad Gateway' },
  ServiceUnavailable: { code: 503, message: 'Service Unavailable' },
  GatewayTimeout: { code: 504, message: 'Gateway Timeout' },
  HTTPVersionNotSupported: { code: 505, message: 'HTTP Version Not Supported' },
  VariantAlsoNegotiates: { code: 506, message: 'Variant Also Negotiates' },
  InsufficientStorage: { code: 507, message: 'Insufficient Storage' },
  LoopDetected: { code: 508, message: 'Loop Detected' },
  BandwidthLimitExceeded: { code: 509, message: 'Bandwidth Limit Exceeded' },
  NotExtended: { code: 510, message: 'Not Extended' },
  NetworkAuthenticationRequired: {
    code: 511,
    message: 'Network Authentication Required'
  }
}
